services:
    # Service de base de données PostgreSQL
    postgres:
        image: postgres:16.4
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        networks:
            - app-network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
            interval: 10s
            timeout: 5s
            retries: 5

    # Service Laravel (application web)
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USERNAME=${DB_USERNAME}
            - DB_DATABASE=${DB_DATABASE}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./:/app
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
        command: sh -c "php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=8000"

    # Service de rotation et analyse des logs
    logrotate:
        build:
            context: .
            dockerfile: Dockerfile.logrotate
        volumes:
            - laravel_logs:/var/log/laravel
        networks:
            - app-network
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4:9.8.0
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
        ports:
            - "8080:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
    laravel_logs:
        driver: local
