<?php

namespace App\Http\Responses;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;

final class ApiResponse
{
    /**
     * Create a fluent builder used to compose API responses.
     *
     * @return ApiResponseBuilder Configured query builder instance.
     */
    public static function builder(): ApiResponseBuilder
    {
        return new ApiResponseBuilder;
    }

    /**
     * Create a success API response with optional payload and message.
     *
     * @param  mixed  $data  Domain payload exposed under the `data` key.
     * @param  ?string  $message  Human-readable status message included in the envelope.
     * @param  int  $status  HTTP status code to send.
     * @param  ?string  $messageCode  Stable machine code used by clients for localization/branching.
     * @param  array  $messageParams  Placeholder values used with the `message_code`.
     * @return JsonResponse JSON API response using the standard envelope.
     */
    public static function success(
        mixed $data = null,
        ?string $message = null,
        int $status = 200,
        ?string $messageCode = 'common.ok',
        array $messageParams = []
    ): JsonResponse {
        return self::builder()
            ->success($status, $message ?? 'Ok')
            ->messageCode($messageCode, $messageParams)
            ->data($data)
            ->json();
    }

    /**
     * Create an error API response with status, message, and error details.
     *
     * @param  ?string  $message  Human-readable error message included in the envelope.
     * @param  int  $status  HTTP status code to send.
     * @param  mixed  $errors  Structured error details attached to the response payload.
     * @param  ?string  $messageCode  Stable machine code used by clients for localization/branching.
     * @param  array  $messageParams  Placeholder values used with the `message_code`.
     * @return JsonResponse JSON API response using the standard envelope.
     */
    public static function error(
        ?string $message = null,
        int $status = 400,
        mixed $errors = null,
        ?string $messageCode = 'common.error',
        array $messageParams = []
    ): JsonResponse {
        return self::builder()
            ->error($status, $message)
            ->messageCode($messageCode, $messageParams)
            ->errors($errors)
            ->json();
    }

    /**
     * Return an HTTP response without a JSON body.
     *
     * @param  int  $status  Requested status value applied by this method.
     * @param  array  $headers  HTTP headers to include in the response.
     * @return Response HTTP response generated by the method.
     */
    public static function noContent(int $status = 204, array $headers = []): Response
    {
        return response()->noContent($status, $headers);
    }

    /**
     * Create a media response builder for file downloads and previews.
     *
     * @return ApiMediaBuilder Configured query builder instance.
     */
    public static function media(): ApiMediaBuilder
    {
        return new ApiMediaBuilder;
    }
}
