<?php

namespace App\Http\Controllers\Tasks;

use App\Domain\Tasks\Actions\TaskActionService;
use App\Domain\Tasks\Queries\TaskQueryService;
use App\Http\Controllers\Controller;
use App\Http\Requests\Task\ListTaskRequest;
use App\Http\Requests\Task\StoreTaskRequest;
use App\Http\Requests\Task\UpdateTaskRequest;
use App\Http\Responses\ApiResponse;
use App\Models\Tasks\Task;
use App\Support\Pagination\OffsetPagination;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class TaskController extends Controller
{
    /**
     * Initialize the controller with task query and command handlers.
     *
     * @param  TaskQueryService  $queryService  Service that loads task lists and visibility-scoped resources.
     * @param  TaskActionService  $actionService  Service that applies task lifecycle state changes.
     */
    public function __construct(
        private readonly TaskQueryService $queryService,
        private readonly TaskActionService $actionService,
    ) {}

    /**
     * List tasks visible to the authenticated user.
     *
     * @param  ListTaskRequest  $request  HTTP request carrying validated parameters for this endpoint.
     * @return JsonResponse JSON API response using the standard envelope.
     */
    public function index(ListTaskRequest $request): JsonResponse
    {
        $validated = $request->validated();
        $pagination = OffsetPagination::extract($validated);

        $tasks = $this->queryService->paginateForUser(
            $request->user(),
            $validated,
            $pagination,
        );

        return ApiResponse::builder()
            ->success()
            ->messageCode('task.list', [])
            ->data($tasks->items())
            ->meta(OffsetPagination::meta($tasks))
            ->json();
    }

    /**
     * Create a new task in the requested theme.
     *
     * @param  StoreTaskRequest  $request  HTTP request carrying validated parameters for this endpoint.
     * @return JsonResponse JSON API response using the standard envelope.
     */
    public function store(StoreTaskRequest $request): JsonResponse
    {
        $validated = $request->validated();
        $theme = $this->queryService->findThemeForCreation((string) $validated['theme_id']);
        $this->authorize('addTask', $theme);

        $task = $this->actionService->create($request->user(), $theme, $validated);

        return ApiResponse::builder()
            ->success(201, 'Created')
            ->messageCode('task.created', ['task' => $task->task_id])
            ->data([
                'task' => $task,
            ])
            ->json();
    }

    /**
     * Return one task visible to the authenticated user.
     *
     * @param  Request  $request  HTTP request carrying validated parameters for this endpoint.
     * @param  Task  $task  Task instance being read or mutated by this method.
     * @return JsonResponse JSON API response using the standard envelope.
     */
    public function show(
        Request $request,
        Task $task
    ): JsonResponse {
        $this->authorize('view', $task);

        return ApiResponse::builder()
            ->success()
            ->messageCode('task.show', ['task' => $task->task_id])
            ->data([
                'task' => $task,
            ])
            ->json();
    }

    /**
     * Update an existing task visible to the authenticated user.
     *
     * @param  UpdateTaskRequest  $request  HTTP request carrying validated parameters for this endpoint.
     * @param  Task  $task  Task instance being read or mutated by this method.
     * @return JsonResponse JSON API response using the standard envelope.
     */
    public function update(UpdateTaskRequest $request, Task $task): JsonResponse
    {
        $this->authorize('update', $task);

        $task = $this->actionService->update($request->user(), $task, $request->validated());

        return ApiResponse::builder()
            ->success()
            ->messageCode('task.updated', ['task' => $task->task_id])
            ->data([
                'task' => $task,
            ])
            ->json();
    }

    /**
     * Delete a task visible to the authenticated user.
     *
     * @param  Request  $request  HTTP request carrying validated parameters for this endpoint.
     * @param  Task  $task  Task instance being read or mutated by this method.
     * @return Response HTTP response generated by the method.
     */
    public function destroy(Request $request, Task $task): Response
    {
        $this->authorize('delete', $task);
        $this->actionService->delete($request->user(), $task);

        return ApiResponse::noContent();
    }
}
